version: "3.8"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - my-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./.docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    #      - './prometheus/data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge